### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by f3ath** [jsonpath-standard/jsonpath-compliance-test-suite#1]
Assuming that the test suite will be getting more strict over time, it seems reasonable to start version it so that the implementations can refer which version of the suite the support. Semver seems to be the natural choice, but it can be extended/replaced with some sort of feature-based versions or tags.

**Comment by glyn** [comment]
I agree it would be very helpful to version the test suite. Actually, it already is if you count a git SHA as a version. But a human readable version would be more helpful. Should this be represented using git tags? This seems better than embedding a version number in the test suite JSON.

Although I generally like semantic versioning, I'm wondering what it would mean for a Compliance Test Suite. Let's consider some examples:
- Add one new test - this is an incompatible change and a major version bump would be necessary
- Rename a test - trivial/compatible change so a micro version bump would be sufficient
- Remove one test - this is a backward compatible change so a minor version bump would be sufficient.

**Comment by f3ath** [comment]
What if we look at it from the test suite standpoint. 
- major: a new feature is covered by the suite, e.g. recursion, a (new) filter expression, etc
- minor a new test is added for an existing feature
- patch: a bug fixed in existing test, a test was renamed or removed


In some sense the test suite is "contravariant" to consumer code, so maybe it should be treated a bit differently in regards to the semver.

**Comment by f3ath** [comment]
I see the following similarities with semver meaning:
- one should not switch to a new major version unless they know what they're doing
- higher minor version is always better
- patch should be as high as possible for the given major and minor

**Comment by glyn** [comment]
> In some sense the test suite is "contravariant" to consumer code, so maybe it should be treated a bit differently in regards to the semver.

 I think this may be a good way of looking at versioning the test suite. Can you flesh it out a bit? I think it's something to do with how an implementation needs to change, or not, to move up to a later version of the test suite.

**Comment by glyn** [comment]
This [definition](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)) of contravariance is helpful.

**Comment by f3ath** [comment]
What are our options here in general?

### 1. Simply use the commit hash.
Pros:
- This is a de-facto mechanism right now, can could just make it formal.
- Not much to do on our side
Cons:
- Not human readable, conveys no knowledge about how far behind the implementation is

### 2. Date
Pros: 
- Easy to implement. 
- Human readable. Tells how long old the version is.
Cons:
- Gives no idea about the actual diff in the test suite between versions
- Collisions are possible, but could be resolved by adding an incremental build number, e.g. `2023-04-29.2`

### 3. Single number 
Pros:
- Easy to implement. 
- Human readable. Roughly tells how far behind the version is.
Cons:
- Gives no idea about the actual diff in the test suite between versions.

### 4. Semver-like
- MAJOR
  - is kept at `0` until the standard reaches the stable version
  - bumped when:
    - a new stable version of the standard is published
    - JSON Schema is changed in a non-compatible way (a field is removed, renamed, changes its meaning)
    - `cts.json` is renamed, moved, split
- MINOR
  - starts with 13 and is kept in sync with https://datatracker.ietf.org/doc/draft-ietf-jsonpath-base/ until the standard reaches the stable version. After that:
  - is bumped when a new test (or a set of tests) is added or an exiting test is renamed.
- PATCH
  - bumped when an incorrect test is fixed or removed. The implementers are expected to keep the CTS at the latest PATCH version regardless of the MAJ/MIN they stick to.

Pros:
- The most insightful in terms of the actual changes
- Widely used and (hopefully) understood

Cons:
- might not always be clear if a change warrants a MAJOR or MINOR bump.

**Comment by gregsdennis** [comment]
I'm not sure we need to version the test suite.  The JSON Schema Test Suite has been active and growing for years (about a decade) without versioning.  What benefits do we get from versioning it?

**Comment by glyn** [comment]
Semver versioning is not particularly intuitive for a test suite.

Also bumping the major version when a new stable version of the standard is published might not make sense. For example, if JSONPath v2 was published, I'd expect to keep a 1.x branch running to continue to test v1 implementations and version the main branch at 2.x. So at the point of publication of JSONPath v2, no action on the CTS would be necessary. Only when we included a test for a v2-specific feature would be need to version to 2.x.

**Comment by gregsdennis** [comment]
> if JSONPath v2 was published, I'd expect to keep a 1.x branch running to continue to test v1 implementations and version the main branch at 2.x

There's no need to manage this with branches.

JSTS keeps folders for each publication of the JSON Schema spec.  It's not on branches.  Implementations can support multiple releases (mine supports 4 of them) just by keeping `main` up to date.

Even so, the test suite itself isn't versioned.

**Comment by glyn** [comment]
Ah yes, makes sense unless v2 contradicts v1 in some way, which seems very
unlikely.
