### ISSUE TITLE
Leading and trailing whitespace tests should be out of scope

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/jsonpath-compliance-test-suite#13]
I don't believe these two tests really apply.  I could have a path embedded in other text (for example in a `jq` command) where surrounding spaces are completely valid (and likely required).

```json
{
  "name": "no leading whitespace",
  "selector": " $",
  "invalid_selector": true
},
{
  "name": "no trailing whitespace",
  "selector": "$ ",
  "invalid_selector": true
}
```

These tests should focus only on the path itself and not consider the context in which it exists.

**Comment by glyn** [comment]
Those tests are based on the ABNF in the spec, which doesn't currently allow leading or trailing whitespace.

If another syntax needs to embed a JSONPath, then the larger syntax should be responsible for parsing what surrounds the JSONPath. For example, if the syntax wanted to embed a JSONPath in parentheses, JSONPath wouldn't then need to allow paths to be enclosed in parentheses. The same goes for whitespace.

**Comment by gregsdennis** [comment]
I understand that the whitespace isn't properly part of JSON Path, but it seems that parsers would benefit from being tolerant of them, especially considering they can be present throughout the syntax.

I don't think these tests belong in the suite.

**Comment by glyn** [comment]
I don't really understand. Are you saying that JSONPath implementations should tolerate whitespace which doesn't conform to the ABNF in the spec?

**Comment by gregsdennis** [comment]
I'm saying that surrounding whitespace doesn't need to be tested.  It's irrelevant.  It's neither valid nor invalid.

**Comment by glyn** [comment]
If we remove these tests, then a JSONPath implementation that allows leading and/or trailing whitespace would pass the CTS, but wouldn't conform to the spec. That doesn't seem right, does it?

**Comment by gregsdennis** [comment]
Yes, that's the point.

The ABNF only applies where the path exists.  That means that anything outside of the path (before or after) is non-specified and irrelevant.

The ABNF _doesn't_ explicitly disallow spaces outside of the path, just as it doesn't explicitly disallow surround `x`s.  Are you going to have a test that `x$` is invalid?  What about `-`s? Or `G`s? No, because this isn't addressed by the ABNF at all.

We should only be testing parsing of _the path_ itself.

**Comment by glyn** [comment]
I agree we should only be testing parsing of the path itself. That's why these tests are there.

If someone wants to embed a JSONPath in a larger expression, e.g. surrounded by whitespace, that's fine, but the parsing of the larger expression should handle the whitespace surrounding the JSONPath.

**Comment by gregsdennis** [comment]
I'm going to concede on this one, but we seem to be arguing the same points and coming to different conclusions.

**Comment by glyn** [comment]
> I'm going to concede on this one, but we seem to be arguing the same points and coming to different conclusions.

It isn't the first time, is it? It's good to have creative tension in the WG!

Thanks for conceding. I was digging in, I'm afraid.
