### ISSUE TITLE
Difference between "overflow" tests and "excessively large" tests - should behave the same

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/jsonpath-compliance-test-suite#14]
```jsonc
{
  "name": "index selector, overflowing index",
  "selector": "$[231584178474632390847141970017375815706539969331281128078915168015826259279872]",
  "invalid_selector": true
}

// and

{
  "name": "slice selector, overflowing to value",
  "selector": "$[2:231584178474632390847141970017375815706539969331281128078915168015826259279872]",
  "invalid_selector": true
}
```

The spec [says](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-09.html#name-index-selector):

> A non-negative index-selector applied to an array selects an array element using a zero-based index. For example, the selector 0 selects the first and the selector 4 selects the fifth element of a sufficiently long array. Nothing is selected, **and it is not an error**, if the index lies outside the range of the array. Nothing is selected from a value that is not an array.

ABNF is (from various parts of the document):

```abnf
int            = "0" / (["-"] DIGIT1 *DIGIT)     ; -  optional
DIGIT1         = %x31-39                         ; 1-9 non-zero digit
DIGIT          =  %x30-39              ; 0-9
```

There's no expressed limit.  I think this is a valid selector, and it should return an empty nodelist.

We do have "excessively large" tests for slice selectors, and these are considered valid even though they'd overflow a 32-bit index.  For example: 

```json
{
  "name": "slice selector, excessively large to value",
  "selector": "$[2:113667776004]",
  "document": [ 0,1, 2, 3, 4, 5, 6, 7, 8, 9 ],
  "result": [ 2, 3, 4, 5, 6, 7, 8, 9 ]
}
```

**Comment by gregsdennis** [comment]
One thing we might want to test for is that an index is not actually a number but starts with sufficient digits to make an implementation attempt to bail early thinking an overflow happened.

```json
{
  "name": "index selector, overflowing index",
  "selector": "$[231584178474632390847141970017375815706539969331281128078915168015AndThenSomeText]",
  "invalid_selector": true
}
```

This is definitely invalid.

**Comment by glyn** [comment]
Section 2.1 of the spec makes it clear that excessively large integers cause syntax errors:

> A string to be used as a JSONPath query needs to be well-formed and valid. A string is a well-formed JSONPath query if it conforms to the ABNF syntax in this document. A well-formed JSONPath query is valid if it also fulfills all semantic requirements posed by this document, which are:
> 1. Integer numbers in the JSONPath query that are relevant to the JSONPath processing (e.g., index values and steps) MUST be within the range of exact values defined in I-JSON [[RFC7493](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#RFC7493)], namely within the interval [-(253)+1, (253)-1].
> 2. Uses of function extensions must be correctly typed, as described in [Section 2.6](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#fnex).
>
> A JSONPath implementation MUST raise an error for any query which is not well-formed and valid.

**Comment by gregsdennis** [comment]
Closed this, but realized I have a follow-up question.

C# only allows 32-bit array indices.  This means that `$[2:113667776004]` can't be supported, although it falls within the range [-(2\**53)+1, (2\**53)-1].

I _can_ include a check that 113667776004 overflows and support that it's just a really big number, but (heaven forbid) if an array actually has that many items in it, I wouldn't be able to process that.  In most cases, it'd be transparent.

**Comment by glyn** [comment]
How could a C# array have that many items in it if array indices are limited to 32 bits?

**Comment by gregsdennis** [comment]
> How could a C# array have that many items in it if array indices are limited to 32 bits?

That's exactly my point.  C# can't handle it, but a JSON array might.  I suspect it would likely fail before it gets to my code.
