### ISSUE TITLE
Split into several files?

### ISSUE THREAD

**Issue by f3ath** [jsonpath-standard/jsonpath-compliance-test-suite#21]
As the test suite grows it might be worth splitting into several files to improve maintainability. As least, maybe, extract the standard functions tests into individual ones. I could craft a PR for that.

**Comment by glyn** [comment]
I'm not sure that splitting the test suite into multiple files would be a
good idea, since as implementation needs to pass the whole suite and having
multiple files increases the risk of certain tests not being run and makes
statements about an implementation having "passed the test suite" (at a
particular SHA/version) ambiguous.

What's the maintenance issue exactly? It seems to me that diffs work well
on large files so long as we avoid unnecessary reformatting.

**Comment by gregsdennis** [comment]
The [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) is very many files, spread across multiple folders.

Multi-file test suites are common, and implementors are familiar with them.  I doubt it will be any issue.

**Comment by f3ath** [comment]
It's becoming irritating to navigate the test suite when adding tests.

**Comment by glyn** [comment]
What's the difficulty exactly? How would you propose to split the test
suite into multiple files? Would it be a single level of splitting or would
it be splitting the file into a tree of files? You see, I'm not sure that
the irritation will go away simply by splitting the file up.

But, regardless of all this, one approach which could be quite elegant
would be to have some kind of (predictable) build step, e.g. in CI, which
combines all the files into a single file for ease of consumption by
JSONPath implementers. WDYT?

If we shipped multiple files instead, then it would be down to all the
implementations to reliably consume all the files, which seems messy to me.

**Comment by f3ath** [comment]
There is already a tree-like structure in the test names. Look:
- slice selector with everything omitted with empty array
- slice selector, negative step with empty array
- filter, greater than or equal to string, single quotes
- filter, greater than or equal to string, double quotes
- filter, count function, non-array/string arg

We have comma separated sections. E.g. "slice selector", "filter" are top level sections, "count function" is a subsection of "filter". I would a least put function tests in their own files.

A dedicated build step seems like a great middle ground. I'll try to make something up.
