### ISSUE TITLE
Validating function arguments at parse time

### ISSUE THREAD

**Issue by hiltontj** [jsonpath-standard/jsonpath-compliance-test-suite#24]
There are several test cases that indicate `ValueType` arguments in functions are validated at parse time for their underlying JSON type. I do not believe that this is correct with respect to the latest version of the spec (base-11). For example, the test `filter, length function, non-array/string arg`:

https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/blob/main/cts.json#L2174

Regarding the `length` function, the spec states that

> Its only argument is an instance of `ValueType`

and that, for any input that is not a string, array, or object,

> [...] the result is `Nothing`.

It seems to me that the query string `"$[?length(1)>=2]"` satisfies these requirements (`length(2)` just produces `Nothing`).

Similar could be said for the following cases:

* `filter, count function, non-array/string arg`
* `filter, match function, invalid first arg`
* `filter, match function, invalid second arg`
* `filter, search function, invalid first arg`
* `filter, search function, invalid second arg`

I understand that, for example, writing `length(2)` doesn't make sense. But requiring validation of literal arguments seems a bit too strict, given that the implementation will have to handle arbitrary JSON data to support the Node variant of the `ValueType`, e.g., `@.a`, anyway.

**Comment by f3ath** [comment]
Is it the same issue which #18 addresses?

**Comment by hiltontj** [comment]
Hey @f3ath - yes, looks like #18 addresses this.

**Comment by gregsdennis** [comment]
I also have those failing after updating to the latest draft.

@hiltontj do you have an implementation? Have you been keeping it up to date?

**Comment by hiltontj** [comment]
Hey @gregsdennis - yes I do. I have been working on the Rust crate [`serde_json_path`](https://github.com/hiltontj/serde_json_path) which intends to implement the standard.

I am keeping it up to date, however, function extensions are the one part that the currently released version of `serde_json_path` does not support. I originally built it referencing base-10, and omitted the function extension because A) it was difficult, and B) I noticed the WG was still iterating on that part of the spec.

I have kept up-to-date with the WG discussions, though, and have been able to get function extensions working (recently I have been referencing the `main` branch in the WG repo).

**Comment by gregsdennis** [comment]
Closing this as it's currently being addressed.

@hiltontj If you'd like, feel free to [join the mailing list](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base#community) or the [unofficial Slack server](https://join.slack.com/t/jsonpath-standard/shared_invite/zt-1rncae4j6-UEe52Yrit6dCNXRuSCu7_A) that was originally set up but eventually declined by IETF because they don't see value in building a community.

**Comment by hiltontj** [comment]
Hey, thanks @gregsdennis - yes this should be closed, thank you and thanks for the invite to the Slack channel - I will join that. I am on the mailing list already.

> was originally set up but eventually declined by IETF 

That's unfortunate, Slack or Discord would be a better UX.
