### ISSUE TITLE
CTS tests?

### ISSUE THREAD

**Issue by f3ath** [jsonpath-standard/jsonpath-compliance-test-suite#26]
It seems that we might benefit from some automated quality gates for the CTS itself. One thing I can imagine is validation against JSON Schema, that would catch typos at least.

**Comment by gregsdennis** [comment]
I think (don't quote me) there is some basic validation that already exists.  @glyn are you aware of any?

**Comment by glyn** [comment]
The only validation I remember is running the CTS against the (now mostly
abandoned) Reference Implementation.

**Comment by gregsdennis** [comment]
Yeah, that's not likely to do much at this point.

JSON Schema could work.  @f3ath would you like to work something up?  I don't see any CI currently; the RI stuff must have been a manual operation.  I think a GH Action would be a good place to start.

**Comment by f3ath** [comment]
Yeah I am willing to try.
