### ISSUE TITLE
Unicode tests don't render correctly in combined _cts.json_

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/jsonpath-compliance-test-suite#38]
@f3ath I think I need your help on this one.  It may be a windows thing, but I'm not sure.

When I run the test combining script `node build tests cts.json`, it mangles any test with unicode.  (I'm running node 16.15.1)

For example:

```jsonc
// from the split file in tests/functions/length.json
{
  "name": "string data, unicode",
  "selector": "$[?length(@)==2]",
  "document": ["☺", "☺☺", "☺☺☺", "ж", "жж", "жжж", "磨", "阿美", "形声字"],
  "result": ["☺☺", "жж", "阿美"]
}

// turns into this in cts.json
{
  "name": "functions, length, string data, unicode",
  "selector": "$[?length(@)==2]",
  "document": [
    "Γÿ║",
    "Γÿ║Γÿ║",
    "Γÿ║Γÿ║Γÿ║",
    "╨╢",
    "╨╢╨╢",
    "╨╢╨╢╨╢",
    "τú¿",
    "Θÿ┐τ╛Ä",
    "σ╜óσú░σ¡ù"
  ],
  "result": [
    "Γÿ║Γÿ║",
    "╨╢╨╢",
    "Θÿ┐τ╛Ä"
  ]
}
```

Then my tests fail (but they pass the original).

**Comment by f3ath** [comment]
I was not able to repro. Tried Node 16.20.0 and 18.16.0 on Win 11 pro with [Git for Windows](https://git-scm.com/download/win). How do you run the generation command?

**Comment by gregsdennis** [comment]
I'll try updating my node.

**Comment by f3ath** [comment]
Try executing `chcp 65001` before running the node. LMK if that helps. I'm crafting another hack to try...

**Comment by f3ath** [comment]
If the thing above does not help, try this version of the script https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/39/files

**Comment by gregsdennis** [comment]
looks like the `chcp 65001` did it.  I've added a powershell script to run the build (alongside the shell script) in #37.  Looks like your #39 also works (in a fresh un-`chcp`'d console).

**Comment by f3ath** [comment]
chcp seems to be a cleaner solution.

**Comment by gregsdennis** [comment]
I can add that to my powershell script, then.

**Comment by gregsdennis** [comment]
Thanks for the help.
