### ISSUE TITLE
ABNF says whitespace should be allowed between root and selector

### ISSUE THREAD

**Issue by graza** [jsonpath-standard/jsonpath-compliance-test-suite#40]
The spec defines the ABNF for a sequence of segments in a query as allowing whitespace before each segment.  There is a number of tests in tests/whitespace/selectors.json that mark queries with such syntax as invalid selectors.  The ABNF is as follows:

```
jsonpath-query      = root-identifier segments
segments            = *(S segment)
root-identifier     = "$"
segment             = child-segment / descendant-segment
```

**Comment by gregsdennis** [comment]
So it does. Los like I missed this one. Can you create a PR fixing these test cases?

**Comment by f3ath** [comment]
Spaces in between segments look weird to my taste. Wondering how widespread this style is "in the wild".

**Comment by gregsdennis** [comment]
The argument for it was being able to place segments on separate lines.  I like to think of things like StackOverflow where you're trying to explain what each part does.

**Comment by graza** [comment]
> Can you create a PR fixing these test cases?

Will do.
