### ISSUE TITLE
Whitespace between "?" and logical-expr 

### ISSUE THREAD

**Issue by jg-rp** [jsonpath-standard/jsonpath-compliance-test-suite#44]
It looks like whitespace is allowed between the question mark of a filter selector and its expression.

```plain
filter-selector     = "?" S logical-expr
```

I don't think there are any test cases covering this yet.

**Comment by f3ath** [comment]
I believe you're right. Would you care to craft a few tests for this and/or #45?

**Comment by jg-rp** [comment]
Sure, I'll attempt a PR or two.
