### ISSUE TITLE
Conflict in tests

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/jsonpath-compliance-test-suite#5]
There are two tests which have exactly the same path:  `$["\u263A"]`.

- `union child, double quotes, escaped ☺` - expected to be valid
- `union child, double quotes, invalid escaped ☺` - expected to be invalid

**Comment by glyn** [comment]
I think the tests being referred to are:
```
    {
      "name": "union child, double quotes, escaped ☺",
      "selector": "$[\"\\u263A\"]",
      "document": {
        "☺": "A"
      },
```
and
```
    {
      "name": "union child, double quotes, invalid escaped ☺",
      "selector": "$[\"\\u263a\"]",
      "invalid_selector": true
    },
```
which have distinct paths.

**Comment by gregsdennis** [comment]
You're saying casing matters for Unicode escapes?  I've never seen that.

[JSON doesn't specify this](https://datatracker.ietf.org/doc/html/rfc7159#section-7); why should JSON Path?  (JSON ABNF actually doesn't define `HEXDIGIT` at all.)

I _do_ see in our WG spec that we define only caps for this, though.  It's there a reason to define this differently than what's allowed by JSON, or to restrict to upper case?

**Comment by glyn** [comment]
> You're saying casing matters for Unicode escapes? I've never seen that.

No, I wasn't saying that. ;-)

> 
> [JSON doesn't specify this](https://datatracker.ietf.org/doc/html/rfc7159#section-7); why should JSON Path? (JSON ABNF actually doesn't define `HEXDIGIT` at all.)
> 
> I _do_ see in our WG spec that we define only caps for this, though. It's there a reason to define this differently than what's allowed by JSON, or to restrict to upper case?

Actually, since writing the CTS, I've learned that ABNF strings are case insensitive. So the CTS needs to be changed so that both tests are valid.
