### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/jsonpath-compliance-test-suite#52]
A recent stackoverflow question raised a potential issue in my implementation, and I thought I'd ask about it before answering the question.

They have data like

```json
[
  {
    "items": [
      { "foo": 1, "bar": "one" },
      { "foo": 2, "bar": "one" }
    ]
  },
  {
    "items": [
      { "foo": 3, "bar": "three" },
      { "foo": 4, "bar": "four" }
    ]
  }
]
```

and they want to get the `bar` value for the item that has `foo: 3`.

In working it out on my playground, I came up with `$..items[?@.foo==3].bar` which returns

```json
[
  {
    "Value": "three",
    "Location": "$[1]['items'][0]['bar']"
  }
]
```

However, then I noticed that I'm not considering that the value of `items` itself is an array.  Testing this, I checked just `$..items` and it returned just the arrays

```json
[
  {
    "Value": [
      {
        "foo": 1,
        "bar": "one"
      },
      {
        "foo": 2,
        "bar": "one"
      }
    ],
    "Location": "$[0]['items']"
  },
  {
    "Value": [
      {
        "foo": 3,
        "bar": "three"
      },
      {
        "foo": 4,
        "bar": "four"
      }
    ],
    "Location": "$[1]['items']"
  }
]
```

This means that somewhere between `$..items` and `$..items[@.foo==3]`, my implementation must be flattening the array, right?

I mean, if I take the "nodelist" result of `$..items`

```json
[
  [
      {
        "foo": 1,
        "bar": "one"
      },
      {
        "foo": 2,
        "bar": "one"
      }
  ],
  [
      {
        "foo": 3,
        "bar": "three"
      },
      {
        "foo": 4,
        "bar": "four"
      }
  ]
]
```

and apply `$[?@.foo==3]` to it, my implementation returns no results.  I think this is what I should expect from the full query & data.

Can someone else confirm, please?

I think we likely need a test for this, either way.  I can work it up once we determine what it should do.

**Comment by gregsdennis** [comment]
I think I may have worked out what's happening.

In the full example, after my implementation processes `$..items`, it has a _nodelist_ of the two arrays under the `items` properties.  Then, _for each node_ in the node list, it applies `[?@.foo==3]`.

So it's applying `[?@.foo==3]` to 

```json
[
  {
    "foo": 1,
    "bar": "one"
  },
  {
    "foo": 2,
    "bar": "one"
  }
]
```

then to 

```json
[
  {
    "foo": 3,
    "bar": "three"
  },
  {
    "foo": 4,
    "bar": "four"
  }
]
```

which properly returns the `foo: 3` object.

This would mean that my implementation is right.

---

The counterintuitive piece is the second part of my analysis above, where breaking apart the segments and running them individually doesn't produce the same result.

This is because it's rendering the nodelist, which has multiple items that need querying, as a single JSON array.

**Comment by hiltontj** [comment]
Hey @gregsdennis ,

Confirming, `serde_json_path` behaves the same way as your implementation, and I believe that is the expected outcome.

In the original scenario, chaining the descendent operator with the filter has the filter applied to two separate nodelists, whose members are objects containing the key `"foo"`, and therefore produces a non-empty query result.

In the latter case, the result is empty because the filter is being applied to a single nodelist, i.e., the root, whose members are arrays, not objects, and therefore do not contain the key `"foo"`.

**Comment by f3ath** [comment]
My implementation behaves the same way. I think the confusion is coming from the "programmer's brain" seeing the `items[?@.foo==3]` part as a single piece, as if it had a higher precedence IYKWIM.

**Comment by gregsdennis** [comment]
Okay. Thanks all.  I guess I just stared at it too long.

**Comment by hiltontj** [comment]
Don't worry, I had to stare for a while too. On the upside, I did manage to clean up some of my tracing instrumentation as a result of this issue 😃
