### ISSUE TITLE
Add branch protection rule

### ISSUE THREAD

**Issue by glyn** [jsonpath-standard/jsonpath-compliance-test-suite#67]
I accidentally pushed to main a few minutes ago - apologies! I'll add a branch protection rule to avoid this happening again.

**Comment by glyn** [comment]
Branch protection rule "main" added. Applies to everyone.

**Comment by Marcono1234** [comment]
This unfortunately broke the workflow for updating `cts.json` (#58), see for example [this workflow run](https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/actions/runs/8458161610/job/23171760401). It seems there [are solutions for this](https://github.com/stefanzweifel/git-auto-commit-action/tree/master?tab=readme-ov-file#push-to-protected-branches) but I am not sure how easy they would be to implement.

**Comment by gregsdennis** [comment]
I can probably take that on next week.

**Comment by gregsdennis** [comment]
@Marcono1234 for now, would you mind pushing a PR to update the cts file directly, please?

**Comment by Marcono1234** [comment]
@gregsdennis, should I do that now already or wait for my other pull requests to be merged first?

**Comment by gregsdennis** [comment]
Actually, good call.  We'll hold one and merge the others.  Then you can rebase the last one and run the consolidation on that.

**Comment by gregsdennis** [comment]
I've recreated the branch protection so that I have override rights.  That means that PRs that I merge (and I'm the only one who can right now) will run the cts generation action partially under my creds and it _should_ be able to continue with the commit.  We'll have to wait for the next PR merge to be sure.
