### ISSUE TITLE
Add catagory to `cts.json`

### ISSUE THREAD

**Issue by He-Pin** [jsonpath-standard/jsonpath-compliance-test-suite#76]
```json
{
      "name": "whitespace, functions, spaces in an absolute singular selector",
      "category": "filter",
      "selector": "$..[?length(@)==length($ [0] .a)]",
      "document": [
        {
          "a": "foo"
        },
        {}
      ],
      "result": [
        "foo"
      ]
    }
```

Would be helpful for testing dedicated group

**Comment by gregsdennis** [comment]
Maybe it could be called `tags`.  I think the one you showed would have `["filter", "equals", "function", "length"]` since it involves all of those things.

**Comment by He-Pin** [comment]
Sorry, I would like to , but under stress at work :(, I can fire a PR If I find time.
