### ISSUE TITLE
Is it too much to add all  the permutions for 

### ISSUE THREAD

**Issue by aljopainter** [jsonpath-standard/jsonpath-compliance-test-suite#82]
I'm looking at `basic.cts` in the the example with: 
`    {
      "name": "descendant segment, object traversal, multiple selectors",
      "selector" : "$..['a','d']",
      "document" : {"x": {"a": "b", "d": "e"}, "y": {"a":"c", "d": "f"}},
      "results": [[
        "b",
        "e",
        "c",
        "f"
      ],[
        "c",
        "f",
        "b",
        "e"
      ]]
    }`

I'm thinking that we could add the other possible permutations to have the complete set:

`
{
   "results": [
      [
         "b",
         "c",
         "e",
         "f"
      ],
      [
         "b",
         "c",
         "f",
         "e"
      ],
      [
         "b",
         "e",
         "c",
         "f"
      ],
      [
         "b",
         "e",
         "f",
         "c"
      ],
      [
         "b",
         "f",
         "c",
         "e"
      ],
      [
         "b",
         "f",
         "e",
         "c"
      ],
      [
         "c",
         "b",
         "e",
         "f"
      ],
      [
         "c",
         "b",
         "f",
         "e"
      ],
      [
         "c",
         "e",
         "b",
         "f"
      ],
      [
         "c",
         "e",
         "f",
         "b"
      ],
      [
         "c",
         "f",
         "b",
         "e"
      ],
      [
         "c",
         "f",
         "e",
         "b"
      ],
      [
         "e",
         "b",
         "c",
         "f"
      ],
      [
         "e",
         "b",
         "f",
         "c"
      ],
      [
         "e",
         "c",
         "b",
         "f"
      ],
      [
         "e",
         "c",
         "f",
         "b"
      ],
      [
         "e",
         "f",
         "b",
         "c"
      ],
      [
         "e",
         "f",
         "c",
         "b"
      ],
      [
         "f",
         "b",
         "c",
         "e"
      ],
      [
         "f",
         "b",
         "e",
         "c"
      ],
      [
         "f",
         "c",
         "b",
         "e"
      ],
      [
         "f",
         "c",
         "e",
         "b"
      ],
      [
         "f",
         "e",
         "b",
         "c"
      ],
      [
         "f",
         "e",
         "c",
         "b"
      ]
   ]
}
`

**Comment by gregsdennis** [comment]
No, the point of the test is that only those listed in `results` are valid.  Nodes must be selected in a particular sequence per the specification.

- Recursive descent - parent nodes before child nodes
- Multiple selectors in `[]` - in selector order

**Comment by aljopainter** [comment]
Understood.  Thanks for explaining.
