### ISSUE TITLE
"functions, length, true arg" return value incorrect?

### ISSUE THREAD

**Issue by EliteMasterEric** [jsonpath-standard/jsonpath-compliance-test-suite#85]
For the following data:

```json
{ "d": "f" }
```

Given the query `$[?length(1)>=2]` (*functions, length, number arg*), the correct result for this query as provided in the test suite is `[]`. This is because `length()`, for any argument which is not a string, array, or object, is `Nothing`, and `Nothing >= 2` evaluates to false, causing the element to not match.

However, for the query `$[?length(true)>=2]` (*functions, length, true arg*), the test suite lists the result as being `[{"d": "f"}]`.

Why is this? What causes `length(true)` to resolve to a value greater than 2? Shouldn't it resolve to Nothing, which causes the comparison to return false since RFC9535 states "A comparison using the operator < yields false."?

**Comment by jg-rp** [comment]
Hi @EliteMasterEric,

From what I can see, both "functions, length, number arg" and "functions, length, true arg" expect a result of `[]`.

https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/blob/87f9420d08cee16a6dddf9b9d6fd43bab4bfc7f6/cts.json#L4848-L4866

**Comment by EliteMasterEric** [comment]
Oops, this appears to have been a copy-paste error with my testing setup.
