### ISSUE TITLE
escape the control char in `name_selector.json`

### ISSUE THREAD

**Issue by He-Pin** [jsonpath-standard/jsonpath-compliance-test-suite#94]
Hi, I'm asking because the `      "selector": "$['\u0001']"` is not somehow parsing correctly in Java with Jackson, which will throw an exception, even if I turned on the 
```
            objectMapper.enable(JsonParser.Feature.ALLOW_UNQUOTED_CONTROL_CHARS);
```

How about we escape it in this repo. to something like `"selector": "$['\\u0001']"`

refs: https://github.com/FasterXML/jackson-core/issues/586

**Comment by gregsdennis** [comment]
No, the point is that the JSON Path string had the control character, unescaped.  We escape it once for the JSON file, but that's it.

**Comment by f3ath** [comment]
I assume you mean this test: https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/blob/9277705cda4489c3d0d984831e7656e48145399b/tests/name_selector.json#L585-L590

```json
    {
      "name": "single quotes, embedded U+0001",
      "selector": "$['\u0001']",
      "invalid_selector": true,
      "tags": ["unicode"]
    },
```
which covers an invalid selector case. `"$['\\u0001']"` would be a valid selector, that's not what we're testing for.

**Comment by He-Pin** [comment]
Yes, that's true, @gregsdennis , I can't load the test cases, not sure why Jackson doesn't work.  thanks @f3ath , the problem is I can't parse the test-suit to a JSONObject, maybe I need work a reproducer , cc @pjfanning

**Comment by He-Pin** [comment]
@gregsdennis After turning on the option, Jackson did the auto conversion, I expected it to keep the raw data
